const CTX_RESET = '#00000000';

// https://colorcodes.io/
// https://gist.github.com/krabs-github/ec56e4f1c12cddf86ae9c551aa9d9e04
// https://chir.ag/projects/ntc/ntc.js
// https://github.com/bahamas10/css-color-names/blob/master/css-color-names.json

class Color {
    #canvas;
    #ctx;

    constructor() {
        this.#canvas = document.createElement('canvas');
        this.#ctx = this.#canvas.getContext('2d', { willReadFrequently: true });
    }

    getName(...color) {
        if (color.length == 1 && typeof color[0] == 'string') {
            if (color[0].startsWith('#')) color[0] = color[0].slice(1);
            const objColor = COLOR_NAMES.find((col) => col.hex == color[0]);
            return objColor ? objColor.name : undefined;            
        } else if (color instanceof Array ) {
            // if first param (red) is already an array we re-assign it!
            if (color[0] instanceof Array) color = color[0];
            let hex = '#';
            for (let i = 0; i < color.length; i++) {
                hex += this.byteToHex(color[i]);
            }
            return this.getName(hex); // recursive call!
        }
    }

    toHex(color) {
        if (typeof color == 'string') {
            if (color.startsWith('#')) return color;
            this.#ctx.fillStyle = CTX_RESET;
            this.#ctx.fillStyle = color;
            return this.#ctx.fillStyle == 'rgba(0, 0, 0, 0)' ? undefined : this.#ctx.fillStyle;
        }    
    }

    /**
     * Turns any valid canvas fill style into an rgba() string. Returns
     * 'rgba(0,0,0,0)' for invalid colors. Examples:
     * color_convert.to_rgba('red')  # 'rgba(255,0,0,1)'
     * color_convert.to_rgba('#f00')  # 'rgba(255,0,0,1)'
     * color_convert.to_rgba('garbagey')  # 'rgba(0,0,0,0)'
     * color_convert.to_rgba(some_pattern)  # Depends on the pattern
     *
     * @param color  A string, pattern, or gradient
     * @return {string} A valid rgba CSS color string
     */    
    toRGBA$(color) {
        if (typeof color == 'string' && !color.startsWith('#')) color = this.toHex(color);        
        const arr = this.#getArrayRGBA(color);
        return `rgba(${arr[0]}, ${arr[1]}, ${arr[2]}, ${(arr[3]/255)})`;
    }
 
    toRGBA(color) {
        if (typeof color == 'string' && !color.startsWith('#')) color = this.toHex(color); 
        // return this.#getArrayRGBA(color).buffer;
        let a = this.#getArrayRGBA(color);
        const arr = [0, 1, 2, 3].map(i => { return a[i] });
        arr[3] = arr[3] / 255;
        return arr;
    }


    // ...color = hsl(0, 0%, 100%)
    // ...color = hwb(0 100% 0%)
    parseColor(...color) {   
        const color$ = color[0];     
        if (color.length == 1 && typeof color$ == 'string') {            
            if (color$.startsWith('#')) { 
                return color$.length == 7 ? color$ : color$.slice(0,4) + color$.slice(1,4);
            } else {
                this.#ctx.fillStyle = CTX_RESET;
                this.#ctx.fillStyle = color;
                return this.#ctx.fillStyle == 'rgba(0, 0, 0, 0)' ? undefined : this.#ctx.fillStyle;
            }                       
        } else if (color instanceof Array ) {            
            // if first param (red!) is already an array we re-assign it!
            if (color$ instanceof Array) color = color$;
            let hex = '#';
            for (let i = 0; i < color.length; i++) {
                hex += this.byteToHex(color[i]);
            }
            return hex;
        }
    }

    /**
     * Turns any valid canvas fillStyle into a 4-element Uint8ClampedArray with bytes
     * for R, G, B, and A. Invalid styles will return [0, 0, 0, 0]. Examples:
     * color_convert.to_rgb_array('red')  # [255, 0, 0, 255]
     * color_convert.to_rgb_array('#ff0000')  # [255, 0, 0, 255]
     * color_convert.to_rgb_array('garbagey')  # [0, 0, 0, 0]
     */
    #getArrayRGBA(color) {
        this.#ctx.fillStyle = CTX_RESET;
        // We're reusing the canvas, so fill it with something predictable
        this.#ctx.clearRect(0, 0, 1, 1);
        this.#ctx.fillStyle = color;
        this.#ctx.fillRect(0, 0, 1, 1);
        return this.#ctx.getImageData(0, 0, 1, 1).data;
    }

    // https://de.wikipedia.org/wiki/YIQ-Farbmodell
    #getYIQvalue(red, green, blue) {
        const contrast = Math.round((red * 299 + green * 587 + blue * 114) / 1000);
        return (contrast > 125) ? 'black' : 'whitesmoke';
    }

    
    /**
     * Converts a number (0-255) into a 2-character hex number (00-FF)
     * @param {number} byte a numeric value from 0-255
     * @returns {string} a hex-string (00 - FF)
     */
    byteToHex(byte) {
        byte = parseInt(byte); // convert possible valid string literals: '255'
        if (typeof byte != 'number') return NaN;
        if (byte < 0 || byte > 255) return undefined;
        return ('0' + byte.toString(16)).slice(-2);
    }
}

export default Color;

const CSS_COLORS = [
    {name: 'aliceblue', hex: 'f0f8ff'}, 
    {name: 'antiquewhite', hex: 'faebd7'}, 
    {name: 'aqua', hex: '00ffff'}, 
    {name: 'aquamarine', hex: '7fffd4'}, 
    {name: 'azure', hex: 'f0ffff'}, 
    {name: 'beige', hex: 'f5f5dc'}, 
    {name: 'bisque', hex: 'ffe4c4'}, 
    {name: 'black', hex: '000000'}, 
    {name: 'blanchedalmond', hex: 'ffebcd'}, 
    {name: 'blue', hex: '0000ff'}, 
    {name: 'blueviolet', hex: '8a2be2'}, 
    {name: 'brown', hex: 'a52a2a'}, 
    {name: 'burlywood', hex: 'deb887'}, 
    {name: 'cadetblue', hex: '5f9ea0'}, 
    {name: 'chartreuse', hex: '7fff00'}, 
    {name: 'chocolate', hex: 'd2691e'}, 
    {name: 'coral', hex: 'ff7f50'}, 
    {name: 'cornflowerblue', hex: '6495ed'}, 
    {name: 'cornsilk', hex: 'fff8dc'}, 
    {name: 'crimson', hex: 'dc143c'}, 
    {name: 'cyan', hex: '00ffff'}, 
    {name: 'darkblue', hex: '00008b'}, 
    {name: 'darkcyan', hex: '008b8b'}, 
    {name: 'darkgoldenrod', hex: 'b8860b'}, 
    {name: 'darkgray', hex: 'a9a9a9'}, 
    {name: 'darkgreen', hex: '006400'}, 
    {name: 'darkgrey', hex: 'a9a9a9'}, 
    {name: 'darkkhaki', hex: 'bdb76b'}, 
    {name: 'darkmagenta', hex: '8b008b'}, 
    {name: 'darkolivegreen', hex: '556b2f'}, 
    {name: 'darkorange', hex: 'ff8c00'}, 
    {name: 'darkorchid', hex: '9932cc'}, 
    {name: 'darkred', hex: '8b0000'}, 
    {name: 'darksalmon', hex: 'e9967a'}, 
    {name: 'darkseagreen', hex: '8fbc8f'}, 
    {name: 'darkslateblue', hex: '483d8b'}, 
    {name: 'darkslategray', hex: '2f4f4f'}, 
    {name: 'darkslategrey', hex: '2f4f4f'}, 
    {name: 'darkturquoise', hex: '00ced1'}, 
    {name: 'darkviolet', hex: '9400d3'}, 
    {name: 'deeppink', hex: 'ff1493'}, 
    {name: 'deepskyblue', hex: '00bfff'}, 
    {name: 'dimgray', hex: '696969'}, 
    {name: 'dimgrey', hex: '696969'}, 
    {name: 'dodgerblue', hex: '1e90ff'}, 
    {name: 'firebrick', hex: 'b22222'}, 
    {name: 'floralwhite', hex: 'fffaf0'}, 
    {name: 'forestgreen', hex: '228b22'}, 
    {name: 'fuchsia', hex: 'ff00ff'}, 
    {name: 'gainsboro', hex: 'dcdcdc'}, 
    {name: 'ghostwhite', hex: 'f8f8ff'}, 
    {name: 'goldenrod', hex: 'daa520'}, 
    {name: 'gold', hex: 'ffd700'}, 
    {name: 'gray', hex: '808080'}, 
    {name: 'green', hex: '008000'}, 
    {name: 'greenyellow', hex: 'adff2f'}, 
    {name: 'grey', hex: '808080'}, 
    {name: 'honeydew', hex: 'f0fff0'}, 
    {name: 'hotpink', hex: 'ff69b4'}, 
    {name: 'indianred', hex: 'cd5c5c'}, 
    {name: 'indigo', hex: '4b0082'}, 
    {name: 'ivory', hex: 'fffff0'}, 
    {name: 'khaki', hex: 'f0e68c'}, 
    {name: 'lavenderblush', hex: 'fff0f5'}, 
    {name: 'lavender', hex: 'e6e6fa'}, 
    {name: 'lawngreen', hex: '7cfc00'}, 
    {name: 'lemonchiffon', hex: 'fffacd'}, 
    {name: 'lightblue', hex: 'add8e6'}, 
    {name: 'lightcoral', hex: 'f08080'}, 
    {name: 'lightcyan', hex: 'e0ffff'}, 
    {name: 'lightgoldenrodyellow', hex: 'fafad2'}, 
    {name: 'lightgray', hex: 'd3d3d3'}, 
    {name: 'lightgreen', hex: '90ee90'}, 
    {name: 'lightgrey', hex: 'd3d3d3'}, 
    {name: 'lightpink', hex: 'ffb6c1'}, 
    {name: 'lightsalmon', hex: 'ffa07a'}, 
    {name: 'lightseagreen', hex: '20b2aa'}, 
    {name: 'lightskyblue', hex: '87cefa'}, 
    {name: 'lightslategray', hex: '778899'}, 
    {name: 'lightslategrey', hex: '778899'}, 
    {name: 'lightsteelblue', hex: 'b0c4de'}, 
    {name: 'lightyellow', hex: 'ffffe0'}, 
    {name: 'lime', hex: '00ff00'}, 
    {name: 'limegreen', hex: '32cd32'}, 
    {name: 'linen', hex: 'faf0e6'}, 
    {name: 'magenta', hex: 'ff00ff'}, 
    {name: 'maroon', hex: '800000'}, 
    {name: 'mediumaquamarine', hex: '66cdaa'}, 
    {name: 'mediumblue', hex: '0000cd'}, 
    {name: 'mediumorchid', hex: 'ba55d3'}, 
    {name: 'mediumpurple', hex: '9370db'}, 
    {name: 'mediumseagreen', hex: '3cb371'}, 
    {name: 'mediumslateblue', hex: '7b68ee'}, 
    {name: 'mediumspringgreen', hex: '00fa9a'}, 
    {name: 'mediumturquoise', hex: '48d1cc'}, 
    {name: 'mediumvioletred', hex: 'c71585'}, 
    {name: 'midnightblue', hex: '191970'}, 
    {name: 'mintcream', hex: 'f5fffa'}, 
    {name: 'mistyrose', hex: 'ffe4e1'}, 
    {name: 'moccasin', hex: 'ffe4b5'}, 
    {name: 'navajowhite', hex: 'ffdead'}, 
    {name: 'navy', hex: '000080'}, 
    {name: 'oldlace', hex: 'fdf5e6'}, 
    {name: 'olive', hex: '808000'}, 
    {name: 'olivedrab', hex: '6b8e23'}, 
    {name: 'orange', hex: 'ffa500'}, 
    {name: 'orangered', hex: 'ff4500'}, 
    {name: 'orchid', hex: 'da70d6'}, 
    {name: 'palegoldenrod', hex: 'eee8aa'}, 
    {name: 'palegreen', hex: '98fb98'}, 
    {name: 'paleturquoise', hex: 'afeeee'}, 
    {name: 'palevioletred', hex: 'db7093'}, 
    {name: 'papayawhip', hex: 'ffefd5'}, 
    {name: 'peachpuff', hex: 'ffdab9'}, 
    {name: 'peru', hex: 'cd853f'}, 
    {name: 'pink', hex: 'ffc0cb'}, 
    {name: 'plum', hex: 'dda0dd'}, 
    {name: 'powderblue', hex: 'b0e0e6'}, 
    {name: 'purple', hex: '800080'}, 
    {name: 'rebeccapurple', hex: '663399'}, 
    {name: 'red', hex: 'ff0000'}, 
    {name: 'rosybrown', hex: 'bc8f8f'}, 
    {name: 'royalblue', hex: '4169e1'}, 
    {name: 'saddlebrown', hex: '8b4513'}, 
    {name: 'salmon', hex: 'fa8072'}, 
    {name: 'sandybrown', hex: 'f4a460'}, 
    {name: 'seagreen', hex: '2e8b57'}, 
    {name: 'seashell', hex: 'fff5ee'}, 
    {name: 'sienna', hex: 'a0522d'}, 
    {name: 'silver', hex: 'c0c0c0'}, 
    {name: 'skyblue', hex: '87ceeb'}, 
    {name: 'slateblue', hex: '6a5acd'}, 
    {name: 'slategray', hex: '708090'}, 
    {name: 'slategrey', hex: '708090'}, 
    {name: 'snow', hex: 'fffafa'}, 
    {name: 'springgreen', hex: '00ff7f'}, 
    {name: 'steelblue', hex: '4682b4'}, 
    {name: 'tan', hex: 'd2b48c'}, 
    {name: 'teal', hex: '008080'}, 
    {name: 'thistle', hex: 'd8bfd8'}, 
    {name: 'tomato', hex: 'ff6347'}, 
    {name: 'turquoise', hex: '40e0d0'}, 
    {name: 'violet', hex: 'ee82ee'}, 
    {name: 'wheat', hex: 'f5deb3'}, 
    {name: 'white', hex: 'ffffff'}, 
    {name: 'whitesmoke', hex: 'f5f5f5'}, 
    {name: 'yellow', hex: 'ffff00'}, 
    {name: 'yellowgreen', hex: '9acd32'}
]

const COLOR_NAMES = [
    {hex: '000000', name: 'black'},
    {hex: '000080', name: 'navy'},
    {hex: '00008b', name: 'darkblue'},
    {hex: '0000ff', name: 'blue'},
    {hex: '000741', name: 'stratos'},
    {hex: '001b1c', name: 'swamp'},
    {hex: '002387', name: 'resolution blue'},
    {hex: '002900', name: 'deep fir'},
    {hex: '002e20', name: 'burnham'},
    {hex: '002fa7', name: 'international klein blue'},
    {hex: '003153', name: 'prussian blue'},
    {hex: '003366', name: 'midnight blue'},
    {hex: '003399', name: 'smalt'},
    {hex: '003532', name: 'deep teal'},
    {hex: '003e40', name: 'cyprus'},
    {hex: '004620', name: 'kaitoke green'},
    {hex: '0047ab', name: 'cobalt'},
    {hex: '004816', name: 'crusoe'},
    {hex: '004950', name: 'sherpa blue'},
    {hex: '0056a7', name: 'endeavour'},
    {hex: '00581a', name: 'camarone'},
    {hex: '0066cc', name: 'science blue'},
    {hex: '0066ff', name: 'blue ribbon'},
    {hex: '00755e', name: 'tropical rain forest'},
    {hex: '0076a3', name: 'allports'},
    {hex: '007ba7', name: 'deep cerulean'},
    {hex: '007ec7', name: 'lochmara'},
    {hex: '007fff', name: 'azure radiance'},
    {hex: '008080', name: 'teal'},
    {hex: '0095b6', name: 'bondi blue'},
    {hex: '009dc4', name: 'pacific blue'},
    {hex: '00a693', name: 'persian green'},
    {hex: '00a86b', name: 'jade'},
    {hex: '00cc99', name: 'caribbean green'},
    {hex: '00cccc', name: 'robins egg blue'},
    {hex: '008000', name: 'green'},
    {hex: '00ff00', name: 'lime'},
    {hex: '00ff7f', name: 'spring green'},
    {hex: '00ffff', name: 'cyan / aqua'},
    {hex: '010d1a', name: 'blue charcoal'},
    {hex: '011635', name: 'midnight'},
    {hex: '011d13', name: 'holly'},
    {hex: '012731', name: 'daintree'},
    {hex: '01361c', name: 'cardin green'},
    {hex: '01371a', name: 'county green'},
    {hex: '013e62', name: 'astronaut blue'},
    {hex: '013f6a', name: 'regal blue'},
    {hex: '014b43', name: 'aqua deep'},
    {hex: '015e85', name: 'orient'},
    {hex: '016162', name: 'blue stone'},
    {hex: '016d39', name: 'fun green'},
    {hex: '01796f', name: 'pine green'},
    {hex: '017987', name: 'blue lagoon'},
    {hex: '01826b', name: 'deep sea'},
    {hex: '01a368', name: 'green haze'},
    {hex: '022d15', name: 'english holly'},
    {hex: '02402c', name: 'sherwood green'},
    {hex: '02478e', name: 'congress blue'},
    {hex: '024e46', name: 'evening sea'},
    {hex: '026395', name: 'bahama blue'},
    {hex: '02866f', name: 'observatory'},
    {hex: '02a4d3', name: 'cerulean'},
    {hex: '03163c', name: 'tangaroa'},
    {hex: '032b52', name: 'green vogue'},
    {hex: '036a6e', name: 'mosque'},
    {hex: '041004', name: 'midnight moss'},
    {hex: '041322', name: 'black pearl'},
    {hex: '042e4c', name: 'blue whale'},
    {hex: '044022', name: 'zuccini'},
    {hex: '044259', name: 'teal blue'},
    {hex: '051040', name: 'deep cove'},
    {hex: '051657', name: 'gulf blue'},
    {hex: '055989', name: 'venice blue'},
    {hex: '056f57', name: 'watercourse'},
    {hex: '062a78', name: 'catalina blue'},
    {hex: '063537', name: 'tiber'},
    {hex: '069b81', name: 'gossamer'},
    {hex: '06a189', name: 'niagara'},
    {hex: '073a50', name: 'tarawera'},
    {hex: '080110', name: 'jaguar'},
    {hex: '081910', name: 'black bean'},
    {hex: '082567', name: 'deep sapphire'},
    {hex: '088370', name: 'elf green'},
    {hex: '08e8de', name: 'bright turquoise'},
    {hex: '092256', name: 'downriver'},
    {hex: '09230f', name: 'palm green'},
    {hex: '09255d', name: 'madison'},
    {hex: '093624', name: 'bottle green'},
    {hex: '095859', name: 'deep sea green'},
    {hex: '097f4b', name: 'salem'},
    {hex: '0a001c', name: 'black russian'},
    {hex: '0a480d', name: 'dark fern'},
    {hex: '0a6906', name: 'japanese laurel'},
    {hex: '0a6f75', name: 'atoll'},
    {hex: '0b0b0b', name: 'cod gray'},
    {hex: '0b0f08', name: 'marshland'},
    {hex: '0b1107', name: 'gordons green'},
    {hex: '0b1304', name: 'black forest'},
    {hex: '0b6207', name: 'san felix'},
    {hex: '0bda51', name: 'malachite'},
    {hex: '0c0b1d', name: 'ebony'},
    {hex: '0c0d0f', name: 'woodsmoke'},
    {hex: '0c1911', name: 'racing green'},
    {hex: '0c7a79', name: 'surfie green'},
    {hex: '0c8990', name: 'blue chill'},
    {hex: '0d0332', name: 'black rock'},
    {hex: '0d1117', name: 'bunker'},
    {hex: '0d1c19', name: 'aztec'},
    {hex: '0d2e1c', name: 'bush'},
    {hex: '0e0e18', name: 'cinder'},
    {hex: '0e2a30', name: 'firefly'},
    {hex: '0f2d9e', name: 'torea bay'},
    {hex: '10121d', name: 'vulcan'},
    {hex: '101405', name: 'green waterloo'},
    {hex: '105852', name: 'eden'},
    {hex: '110c6c', name: 'arapawa'},
    {hex: '120a8f', name: 'ultramarine'},
    {hex: '123447', name: 'elephant'},
    {hex: '126b40', name: 'jewel'},
    {hex: '130000', name: 'diesel'},
    {hex: '130a06', name: 'asphalt'},
    {hex: '13264d', name: 'blue zodiac'},
    {hex: '134f19', name: 'parsley'},
    {hex: '140600', name: 'nero'},
    {hex: '1450aa', name: 'tory blue'},
    {hex: '151f4c', name: 'bunting'},
    {hex: '1560bd', name: 'denim'},
    {hex: '15736b', name: 'genoa'},
    {hex: '161928', name: 'mirage'},
    {hex: '161d10', name: 'hunter green'},
    {hex: '162a40', name: 'big stone'},
    {hex: '163222', name: 'celtic'},
    {hex: '16322c', name: 'timber green'},
    {hex: '163531', name: 'gable green'},
    {hex: '171f04', name: 'pine tree'},
    {hex: '175579', name: 'chathams blue'},
    {hex: '182d09', name: 'deep forest green'},
    {hex: '18587a', name: 'blumine'},
    {hex: '19330e', name: 'palm leaf'},
    {hex: '193751', name: 'nile blue'},
    {hex: '1959a8', name: 'fun blue'},
    {hex: '1a1a68', name: 'lucky point'},
    {hex: '1ab385', name: 'mountain meadow'},
    {hex: '1b0245', name: 'tolopea'},
    {hex: '1b1035', name: 'haiti'},
    {hex: '1b127b', name: 'deep koamaru'},
    {hex: '1b1404', name: 'acadia'},
    {hex: '1b2f11', name: 'seaweed'},
    {hex: '1b3162', name: 'biscay'},
    {hex: '1b659d', name: 'matisse'},
    {hex: '1c1208', name: 'crowshead'},
    {hex: '1c1e13', name: 'rangoon green'},
    {hex: '1c39bb', name: 'persian blue'},
    {hex: '1c402e', name: 'everglade'},
    {hex: '1c7c7d', name: 'elm'},
    {hex: '1d6142', name: 'green pea'},
    {hex: '1e0f04', name: 'creole'},
    {hex: '1e1609', name: 'karaka'},
    {hex: '1e1708', name: 'el paso'},
    {hex: '1e385b', name: 'cello'},
    {hex: '1e433c', name: 'te papa green'},
    {hex: '1e90ff', name: 'dodger blue'},
    {hex: '1e9ab0', name: 'eastern blue'},
    {hex: '1f120f', name: 'night rider'},
    {hex: '1fc2c2', name: 'java'},
    {hex: '20208d', name: 'jacksons purple'},
    {hex: '202e54', name: 'cloud burst'},
    {hex: '204852', name: 'blue dianne'},
    {hex: '211a0e', name: 'eternity'},
    {hex: '220878', name: 'deep blue'},
    {hex: '228b22', name: 'forest green'},
    {hex: '233418', name: 'mallard'},
    {hex: '240a40', name: 'violet'},
    {hex: '240c02', name: 'kilamanjaro'},
    {hex: '242a1d', name: 'log cabin'},
    {hex: '242e16', name: 'black olive'},
    {hex: '24500f', name: 'green house'},
    {hex: '251607', name: 'graphite'},
    {hex: '251706', name: 'cannon black'},
    {hex: '251f4f', name: 'port gore'},
    {hex: '25272c', name: 'shark'},
    {hex: '25311c', name: 'green kelp'},
    {hex: '2596d1', name: 'curious blue'},
    {hex: '260368', name: 'paua'},
    {hex: '26056a', name: 'paris m'},
    {hex: '261105', name: 'wood bark'},
    {hex: '261414', name: 'gondola'},
    {hex: '262335', name: 'steel gray'},
    {hex: '26283b', name: 'ebony clay'},
    {hex: '273a81', name: 'bay of many'},
    {hex: '27504b', name: 'plantation'},
    {hex: '278a5b', name: 'eucalyptus'},
    {hex: '281e15', name: 'oil'},
    {hex: '283a77', name: 'astronaut'},
    {hex: '286acd', name: 'mariner'},
    {hex: '290c5e', name: 'violent violet'},
    {hex: '292130', name: 'bastille'},
    {hex: '292319', name: 'zeus'},
    {hex: '292937', name: 'charade'},
    {hex: '297b9a', name: 'jelly bean'},
    {hex: '29ab87', name: 'jungle green'},
    {hex: '2a0359', name: 'cherry pie'},
    {hex: '2a140e', name: 'coffee bean'},
    {hex: '2a2630', name: 'baltic sea'},
    {hex: '2a380b', name: 'turtle green'},
    {hex: '2a52be', name: 'cerulean blue'},
    {hex: '2b0202', name: 'sepia black'},
    {hex: '2b194f', name: 'valhalla'},
    {hex: '2b3228', name: 'heavy metal'},
    {hex: '2c0e8c', name: 'blue gem'},
    {hex: '2c1632', name: 'revolver'},
    {hex: '2c2133', name: 'bleached cedar'},
    {hex: '2c8c84', name: 'lochinvar'},
    {hex: '2d2510', name: 'mikado'},
    {hex: '2d383a', name: 'outer space'},
    {hex: '2d569b', name: 'st tropaz'},
    {hex: '2e0329', name: 'jacaranda'},
    {hex: '2e1905', name: 'jacko bean'},
    {hex: '2e3222', name: 'rangitoto'},
    {hex: '2e3f62', name: 'rhino'},
    {hex: '2e8b57', name: 'sea green'},
    {hex: '2ebfd4', name: 'scooter'},
    {hex: '2f270e', name: 'onion'},
    {hex: '2f3cb3', name: 'governor bay'},
    {hex: '2f519e', name: 'sapphire'},
    {hex: '2f5a57', name: 'spectra'},
    {hex: '2f6168', name: 'casal'},
    {hex: '300529', name: 'melanzane'},
    {hex: '301f1e', name: 'cocoa brown'},
    {hex: '302a0f', name: 'woodrush'},
    {hex: '304b6a', name: 'san juan'},
    {hex: '30d5c8', name: 'turquoise'},
    {hex: '311c17', name: 'eclipse'},
    {hex: '314459', name: 'pickled bluewood'},
    {hex: '315ba1', name: 'azure'},
    {hex: '31728d', name: 'calypso'},
    {hex: '317d82', name: 'paradiso'},
    {hex: '32127a', name: 'persian indigo'},
    {hex: '32293a', name: 'blackcurrant'},
    {hex: '323232', name: 'mine shaft'},
    {hex: '325d52', name: 'stromboli'},
    {hex: '327c14', name: 'bilbao'},
    {hex: '327da0', name: 'astral'},
    {hex: '33036b', name: 'christalle'},
    {hex: '33292f', name: 'thunder'},
    {hex: '33cc99', name: 'shamrock'},
    {hex: '341515', name: 'tamarind'},
    {hex: '350036', name: 'mardi gras'},
    {hex: '350e42', name: 'valentino'},
    {hex: '350e57', name: 'jagger'},
    {hex: '353542', name: 'tuna'},
    {hex: '354e8c', name: 'chambray'},
    {hex: '363050', name: 'martinique'},
    {hex: '363534', name: 'tuatara'},
    {hex: '363c0d', name: 'waiouru'},
    {hex: '36747d', name: 'ming'},
    {hex: '368716', name: 'la palma'},
    {hex: '370202', name: 'chocolate'},
    {hex: '371d09', name: 'clinker'},
    {hex: '37290e', name: 'brown tumbleweed'},
    {hex: '373021', name: 'birch'},
    {hex: '377475', name: 'oracle'},
    {hex: '380474', name: 'blue diamond'},
    {hex: '381a51', name: 'grape'},
    {hex: '383533', name: 'dune'},
    {hex: '384555', name: 'oxford blue'},
    {hex: '384910', name: 'clover'},
    {hex: '394851', name: 'limed spruce'},
    {hex: '396413', name: 'dell'},
    {hex: '3a0020', name: 'toledo'},
    {hex: '3a2010', name: 'sambuca'},
    {hex: '3a2a6a', name: 'jacarta'},
    {hex: '3a686c', name: 'william'},
    {hex: '3a6a47', name: 'killarney'},
    {hex: '3ab09e', name: 'keppel'},
    {hex: '3b000b', name: 'temptress'},
    {hex: '3b0910', name: 'aubergine'},
    {hex: '3b1f1f', name: 'jon'},
    {hex: '3b2820', name: 'treehouse'},
    {hex: '3b7a57', name: 'amazon'},
    {hex: '3b91b4', name: 'boston blue'},
    {hex: '3c0878', name: 'windsor'},
    {hex: '3c1206', name: 'rebel'},
    {hex: '3c1f76', name: 'meteorite'},
    {hex: '3c2005', name: 'dark ebony'},
    {hex: '3c3910', name: 'camouflage'},
    {hex: '3c4151', name: 'bright gray'},
    {hex: '3c4443', name: 'cape cod'},
    {hex: '3c493a', name: 'lunar green'},
    {hex: '3d0c02', name: 'bean  '},
    {hex: '3d2b1f', name: 'bistre'},
    {hex: '3d7d52', name: 'goblin'},
    {hex: '3e0480', name: 'kingfisher daisy'},
    {hex: '3e1c14', name: 'cedar'},
    {hex: '3e2b23', name: 'english walnut'},
    {hex: '3e2c1c', name: 'black marlin'},
    {hex: '3e3a44', name: 'ship gray'},
    {hex: '3eabbf', name: 'pelorous'},
    {hex: '3f2109', name: 'bronze'},
    {hex: '3f2500', name: 'cola'},
    {hex: '3f3002', name: 'madras'},
    {hex: '3f307f', name: 'minsk'},
    {hex: '3f4c3a', name: 'cabbage pont'},
    {hex: '3f583b', name: 'tom thumb'},
    {hex: '3f5d53', name: 'mineral green'},
    {hex: '3fc1aa', name: 'puerto rico'},
    {hex: '3fff00', name: 'harlequin'},
    {hex: '401801', name: 'brown pod'},
    {hex: '40291d', name: 'cork'},
    {hex: '403b38', name: 'masala'},
    {hex: '403d19', name: 'thatch green'},
    {hex: '405169', name: 'fiord'},
    {hex: '40826d', name: 'viridian'},
    {hex: '40a860', name: 'chateau green'},
    {hex: '410056', name: 'ripe plum'},
    {hex: '411f10', name: 'paco'},
    {hex: '412010', name: 'deep oak'},
    {hex: '413c37', name: 'merlin'},
    {hex: '414257', name: 'gun powder'},
    {hex: '414c7d', name: 'east bay'},
    {hex: '4169e1', name: 'royal blue'},
    {hex: '41aa78', name: 'ocean green'},
    {hex: '420303', name: 'burnt maroon'},
    {hex: '423921', name: 'lisbon brown'},
    {hex: '427977', name: 'faded jade'},
    {hex: '431560', name: 'scarlet gum'},
    {hex: '433120', name: 'iroko'},
    {hex: '433e37', name: 'armadillo'},
    {hex: '434c59', name: 'river bed'},
    {hex: '436a0d', name: 'green leaf'},
    {hex: '44012d', name: 'barossa'},
    {hex: '441d00', name: 'morocco brown'},
    {hex: '444954', name: 'mako'},
    {hex: '454936', name: 'kelp'},
    {hex: '456cac', name: 'san marino'},
    {hex: '45b1e8', name: 'picton blue'},
    {hex: '460b41', name: 'loulou'},
    {hex: '462425', name: 'crater brown'},
    {hex: '465945', name: 'gray asparagus'},
    {hex: '4682b4', name: 'steel blue'},
    {hex: '480404', name: 'rustic red'},
    {hex: '480607', name: 'bulgarian rose'},
    {hex: '480656', name: 'clairvoyant'},
    {hex: '481c1c', name: 'cocoa bean'},
    {hex: '483131', name: 'woody brown'},
    {hex: '483c32', name: 'taupe'},
    {hex: '49170c', name: 'van cleef'},
    {hex: '492615', name: 'brown derby'},
    {hex: '49371b', name: 'metallic bronze'},
    {hex: '495400', name: 'verdun green'},
    {hex: '496679', name: 'blue bayoux'},
    {hex: '497183', name: 'bismark'},
    {hex: '4a2a04', name: 'bracken'},
    {hex: '4a3004', name: 'deep bronze'},
    {hex: '4a3c30', name: 'mondo'},
    {hex: '4a4244', name: 'tundora'},
    {hex: '4a444b', name: 'gravel'},
    {hex: '4a4e5a', name: 'trout'},
    {hex: '4b0082', name: 'pigment indigo'},
    {hex: '4b5d52', name: 'nandor'},
    {hex: '4c3024', name: 'saddle'},
    {hex: '4c4f56', name: 'abbey'},
    {hex: '4d0135', name: 'blackberry'},
    {hex: '4d0a18', name: 'cab sav'},
    {hex: '4d1e01', name: 'indian tan'},
    {hex: '4d282d', name: 'cowboy'},
    {hex: '4d282e', name: 'livid brown'},
    {hex: '4d3833', name: 'rock'},
    {hex: '4d3d14', name: 'punga'},
    {hex: '4d400f', name: 'bronzetone'},
    {hex: '4d5328', name: 'woodland'},
    {hex: '4e0606', name: 'mahogany'},
    {hex: '4e2a5a', name: 'bossanova'},
    {hex: '4e3b41', name: 'matterhorn'},
    {hex: '4e420c', name: 'bronze olive'},
    {hex: '4e4562', name: 'mulled wine'},
    {hex: '4e6649', name: 'axolotl'},
    {hex: '4e7f9e', name: 'wedgewood'},
    {hex: '4eabd1', name: 'shakespeare'},
    {hex: '4f1c70', name: 'honey flower'},
    {hex: '4f2398', name: 'daisy bush'},
    {hex: '4f69c6', name: 'indigo'},
    {hex: '4f7942', name: 'fern green'},
    {hex: '4f9d5d', name: 'fruit salad'},
    {hex: '4fa83d', name: 'apple'},
    {hex: '504351', name: 'mortar'},
    {hex: '507096', name: 'kashmir blue'},
    {hex: '507672', name: 'cutty sark'},
    {hex: '50c878', name: 'emerald'},
    {hex: '514649', name: 'emperor'},
    {hex: '516e3d', name: 'chalet green'},
    {hex: '517c66', name: 'como'},
    {hex: '51808f', name: 'smalt blue'},
    {hex: '52001f', name: 'castro'},
    {hex: '520c17', name: 'maroon oak'},
    {hex: '523c94', name: 'gigas'},
    {hex: '533455', name: 'voodoo'},
    {hex: '534491', name: 'victoria'},
    {hex: '53824b', name: 'hippie green'},
    {hex: '541012', name: 'heath'},
    {hex: '544333', name: 'judge gray'},
    {hex: '54534d', name: 'fuscous gray'},
    {hex: '549019', name: 'vida loca'},
    {hex: '55280c', name: 'cioccolato'},
    {hex: '555b10', name: 'saratoga'},
    {hex: '556d56', name: 'finlandia'},
    {hex: '5590d9', name: 'havelock blue'},
    {hex: '56b4be', name: 'fountain blue'},
    {hex: '578363', name: 'spring leaves'},
    {hex: '583401', name: 'saddle brown'},
    {hex: '585562', name: 'scarpa flow'},
    {hex: '587156', name: 'cactus'},
    {hex: '589aaf', name: 'hippie blue'},
    {hex: '591d35', name: 'wine berry'},
    {hex: '592804', name: 'brown bramble'},
    {hex: '593737', name: 'congo brown'},
    {hex: '594433', name: 'millbrook'},
    {hex: '5a6e9c', name: 'waikawa gray'},
    {hex: '5a87a0', name: 'horizon'},
    {hex: '5b3013', name: 'jambalaya'},
    {hex: '5c0120', name: 'bordeaux'},
    {hex: '5c0536', name: 'mulberry wood'},
    {hex: '5c2e01', name: 'carnaby tan'},
    {hex: '5c5d75', name: 'comet'},
    {hex: '5d1e0f', name: 'redwood'},
    {hex: '5d4c51', name: 'don juan'},
    {hex: '5d5c58', name: 'chicago'},
    {hex: '5d5e37', name: 'verdigris'},
    {hex: '5d7747', name: 'dingley'},
    {hex: '5da19f', name: 'breaker bay'},
    {hex: '5e483e', name: 'kabul'},
    {hex: '5e5d3b', name: 'hemlock'},
    {hex: '5f3d26', name: 'irish coffee'},
    {hex: '5f5f6e', name: 'mid gray'},
    {hex: '5f6672', name: 'shuttle gray'},
    {hex: '5fa777', name: 'aqua forest'},
    {hex: '5fb3ac', name: 'tradewind'},
    {hex: '604913', name: 'horses neck'},
    {hex: '605b73', name: 'smoky'},
    {hex: '606e68', name: 'corduroy'},
    {hex: '6093d1', name: 'danube'},
    {hex: '612718', name: 'espresso'},
    {hex: '614051', name: 'eggplant'},
    {hex: '615d30', name: 'costa del sol'},
    {hex: '61845f', name: 'glade green'},
    {hex: '622f30', name: 'buccaneer'},
    {hex: '623f2d', name: 'quincy'},
    {hex: '624e9a', name: 'butterfly bush'},
    {hex: '625119', name: 'west coast'},
    {hex: '626649', name: 'finch'},
    {hex: '639a8f', name: 'patina'},
    {hex: '63b76c', name: 'fern'},
    {hex: '6456b7', name: 'blue violet'},
    {hex: '646077', name: 'dolphin'},
    {hex: '646463', name: 'storm dust'},
    {hex: '646a54', name: 'siam'},
    {hex: '646e75', name: 'nevada'},
    {hex: '6495ed', name: 'cornflower blue'},
    {hex: '64ccdb', name: 'viking'},
    {hex: '65000b', name: 'rosewood'},
    {hex: '651a14', name: 'cherrywood'},
    {hex: '652dc1', name: 'purple heart'},
    {hex: '657220', name: 'fern frond'},
    {hex: '65745d', name: 'willow grove'},
    {hex: '65869f', name: 'hoki'},
    {hex: '660045', name: 'pompadour'},
    {hex: '660099', name: 'purple'},
    {hex: '66023c', name: 'tyrian purple'},
    {hex: '661010', name: 'dark tan'},
    {hex: '66b58f', name: 'silver tree'},
    {hex: '66ff00', name: 'bright green'},
    {hex: '66ff66', name: 'screaming green'},
    {hex: '67032d', name: 'black rose'},
    {hex: '675fa6', name: 'scampi'},
    {hex: '676662', name: 'ironside gray'},
    {hex: '678975', name: 'viridian green'},
    {hex: '67a712', name: 'christi'},
    {hex: '683600', name: 'nutmeg wood finish'},
    {hex: '685558', name: 'zambezi'},
    {hex: '685e6e', name: 'salt box'},
    {hex: '692545', name: 'tawny port'},
    {hex: '692d54', name: 'finn'},
    {hex: '695f62', name: 'scorpion'},
    {hex: '697e9a', name: 'lynch'},
    {hex: '6a442e', name: 'spice'},
    {hex: '6a5d1b', name: 'himalaya'},
    {hex: '6a6051', name: 'soya bean'},
    {hex: '6b2a14', name: 'hairy heath'},
    {hex: '6b3fa0', name: 'royal purple'},
    {hex: '6b4e31', name: 'shingle fawn'},
    {hex: '6b5755', name: 'dorado'},
    {hex: '6b8ba2', name: 'bermuda gray'},
    {hex: '6b8e23', name: 'olive drab'},
    {hex: '6c3082', name: 'eminence'},
    {hex: '6cdae7', name: 'turquoise blue'},
    {hex: '6d0101', name: 'lonestar'},
    {hex: '6d5e54', name: 'pine cone'},
    {hex: '6d6c6c', name: 'dove gray'},
    {hex: '6d9292', name: 'juniper'},
    {hex: '6d92a1', name: 'gothic'},
    {hex: '6e0902', name: 'red oxide'},
    {hex: '6e1d14', name: 'moccaccino'},
    {hex: '6e4826', name: 'pickled bean'},
    {hex: '6e4b26', name: 'dallas'},
    {hex: '6e6d57', name: 'kokoda'},
    {hex: '6e7783', name: 'pale sky'},
    {hex: '6f440c', name: 'cafe royale'},
    {hex: '6f6a61', name: 'flint'},
    {hex: '6f8e63', name: 'highland'},
    {hex: '6f9d02', name: 'limeade'},
    {hex: '6fd0c5', name: 'downy'},
    {hex: '701c1c', name: 'persian plum'},
    {hex: '704214', name: 'sepia'},
    {hex: '704a07', name: 'antique bronze'},
    {hex: '704f50', name: 'ferra'},
    {hex: '706555', name: 'coffee'},
    {hex: '708090', name: 'slate gray'},
    {hex: '711a00', name: 'cedar wood finish'},
    {hex: '71291d', name: 'metallic copper'},
    {hex: '714693', name: 'affair'},
    {hex: '714ab2', name: 'studio'},
    {hex: '715d47', name: 'tobacco brown'},
    {hex: '716338', name: 'yellow metal'},
    {hex: '716b56', name: 'peat'},
    {hex: '716e10', name: 'olivetone'},
    {hex: '717486', name: 'storm gray'},
    {hex: '718080', name: 'sirocco'},
    {hex: '71d9e2', name: 'aquamarine blue'},
    {hex: '72010f', name: 'venetian red'},
    {hex: '724a2f', name: 'old copper'},
    {hex: '726d4e', name: 'go ben'},
    {hex: '727b89', name: 'raven'},
    {hex: '731e8f', name: 'seance'},
    {hex: '734a12', name: 'raw umber'},
    {hex: '736c9f', name: 'kimberly'},
    {hex: '736d58', name: 'crocodile'},
    {hex: '737829', name: 'crete'},
    {hex: '738678', name: 'xanadu'},
    {hex: '74640d', name: 'spicy mustard'},
    {hex: '747d63', name: 'limed ash'},
    {hex: '747d83', name: 'rolling stone'},
    {hex: '748881', name: 'blue smoke'},
    {hex: '749378', name: 'laurel'},
    {hex: '74c365', name: 'mantis'},
    {hex: '755a57', name: 'russett'},
    {hex: '7563a8', name: 'deluge'},
    {hex: '76395d', name: 'cosmic'},
    {hex: '7666c6', name: 'blue marguerite'},
    {hex: '76bd17', name: 'lima'},
    {hex: '76d7ea', name: 'sky blue'},
    {hex: '770f05', name: 'dark burgundy'},
    {hex: '771f1f', name: 'crown of thorns'},
    {hex: '773f1a', name: 'walnut'},
    {hex: '776f61', name: 'pablo'},
    {hex: '778120', name: 'pacifika'},
    {hex: '779e86', name: 'oxley'},
    {hex: '77dd77', name: 'pastel green'},
    {hex: '780109', name: 'japanese maple'},
    {hex: '782d19', name: 'mocha'},
    {hex: '782f16', name: 'peanut'},
    {hex: '78866b', name: 'camouflage green'},
    {hex: '788a25', name: 'wasabi'},
    {hex: '788bba', name: 'ship cove'},
    {hex: '78a39c', name: 'sea nymph'},
    {hex: '795d4c', name: 'roman coffee'},
    {hex: '796878', name: 'old lavender'},
    {hex: '796989', name: 'rum'},
    {hex: '796a78', name: 'fedora'},
    {hex: '796d62', name: 'sandstone'},
    {hex: '79deec', name: 'spray'},
    {hex: '7a013a', name: 'siren'},
    {hex: '7a58c1', name: 'fuchsia blue'},
    {hex: '7a7a7a', name: 'boulder'},
    {hex: '7a89b8', name: 'wild blue yonder'},
    {hex: '7ac488', name: 'de york'},
    {hex: '7b3801', name: 'red beech'},
    {hex: '7b3f00', name: 'cinnamon'},
    {hex: '7b6608', name: 'yukon gold'},
    {hex: '7b7874', name: 'tapa'},
    {hex: '7b7c94', name: 'waterloo '},
    {hex: '7b8265', name: 'flax smoke'},
    {hex: '7b9f80', name: 'amulet'},
    {hex: '7ba05b', name: 'asparagus'},
    {hex: '7c1c05', name: 'kenyan copper'},
    {hex: '7c7631', name: 'pesto'},
    {hex: '7c778a', name: 'topaz'},
    {hex: '7c7b7a', name: 'concord'},
    {hex: '7c7b82', name: 'jumbo'},
    {hex: '7c881a', name: 'trendy green'},
    {hex: '7ca1a6', name: 'gumbo'},
    {hex: '7cb0a1', name: 'acapulco'},
    {hex: '7cb7bb', name: 'neptune'},
    {hex: '7d2c14', name: 'pueblo'},
    {hex: '7da98d', name: 'bay leaf'},
    {hex: '7dc8f7', name: 'malibu'},
    {hex: '7dd8c6', name: 'bermuda'},
    {hex: '7e3a15', name: 'copper canyon'},
    {hex: '7f1734', name: 'claret'},
    {hex: '7f3a02', name: 'peru tan'},
    {hex: '7f626d', name: 'falcon'},
    {hex: '7f7589', name: 'mobster'},
    {hex: '7f76d3', name: 'moody blue'},
    {hex: '7fff00', name: 'chartreuse'},
    {hex: '7fffd4', name: 'aquamarine'},
    {hex: '800000', name: 'maroon'},
    {hex: '800b47', name: 'rose bud cherry'},
    {hex: '801818', name: 'falu red'},
    {hex: '80341f', name: 'red robin'},
    {hex: '803790', name: 'vivid violet'},
    {hex: '80461b', name: 'russet'},
    {hex: '807e79', name: 'friar gray'},
    {hex: '808000', name: 'olive'},
    {hex: '808080', name: 'gray'},
    {hex: '80b3ae', name: 'gulf stream'},
    {hex: '80b3c4', name: 'glacier'},
    {hex: '80ccea', name: 'seagull'},
    {hex: '81422c', name: 'nutmeg'},
    {hex: '816e71', name: 'spicy pink'},
    {hex: '817377', name: 'empress'},
    {hex: '819885', name: 'spanish green'},
    {hex: '826f65', name: 'sand dune'},
    {hex: '828685', name: 'gunsmoke'},
    {hex: '828f72', name: 'battleship gray'},
    {hex: '831923', name: 'merlot'},
    {hex: '837050', name: 'shadow'},
    {hex: '83aa5d', name: 'chelsea cucumber'},
    {hex: '83d0c6', name: 'monte carlo'},
    {hex: '843179', name: 'plum'},
    {hex: '84a0a0', name: 'granny smith'},
    {hex: '8581d9', name: 'chetwode blue'},
    {hex: '858470', name: 'bandicoot'},
    {hex: '859faf', name: 'bali hai'},
    {hex: '85c4cc', name: 'half baked'},
    {hex: '860111', name: 'red devil'},
    {hex: '863c3c', name: 'lotus'},
    {hex: '86483c', name: 'ironstone'},
    {hex: '864d1e', name: 'bull shot'},
    {hex: '86560a', name: 'rusty nail'},
    {hex: '868974', name: 'bitter'},
    {hex: '86949f', name: 'regent gray'},
    {hex: '871550', name: 'disco'},
    {hex: '87756e', name: 'americano'},
    {hex: '877c7b', name: 'hurricane'},
    {hex: '878d91', name: 'oslo gray'},
    {hex: '87ab39', name: 'sushi'},
    {hex: '885342', name: 'spicy mix'},
    {hex: '886221', name: 'kumera'},
    {hex: '888387', name: 'suva gray'},
    {hex: '888d65', name: 'avocado'},
    {hex: '893456', name: 'camelot'},
    {hex: '893843', name: 'solid pink'},
    {hex: '894367', name: 'cannon pink'},
    {hex: '897d6d', name: 'makara'},
    {hex: '8a3324', name: 'burnt umber'},
    {hex: '8a73d6', name: 'true v'},
    {hex: '8a8360', name: 'clay creek'},
    {hex: '8a8389', name: 'monsoon'},
    {hex: '8a8f8a', name: 'stack'},
    {hex: '8ab9f1', name: 'jordy blue'},
    {hex: '8b00ff', name: 'electric violet'},
    {hex: '8b0723', name: 'monarch'},
    {hex: '8b6b0b', name: 'corn harvest'},
    {hex: '8b8470', name: 'olive haze'},
    {hex: '8b847e', name: 'schooner'},
    {hex: '8b8680', name: 'natural gray'},
    {hex: '8b9c90', name: 'mantle'},
    {hex: '8b9fee', name: 'portage'},
    {hex: '8ba690', name: 'envy'},
    {hex: '8ba9a5', name: 'cascade'},
    {hex: '8be6d8', name: 'riptide'},
    {hex: '8c055e', name: 'cardinal pink'},
    {hex: '8c472f', name: 'mule fawn'},
    {hex: '8c5738', name: 'potters clay'},
    {hex: '8c6495', name: 'trendy pink'},
    {hex: '8d0226', name: 'paprika'},
    {hex: '8d3d38', name: 'sanguine brown'},
    {hex: '8d3f3f', name: 'tosca'},
    {hex: '8d7662', name: 'cement'},
    {hex: '8d8974', name: 'granite green'},
    {hex: '8d90a1', name: 'manatee'},
    {hex: '8da8cc', name: 'polo blue'},
    {hex: '8e0000', name: 'red berry'},
    {hex: '8e4d1e', name: 'rope'},
    {hex: '8e6f70', name: 'opium'},
    {hex: '8e775e', name: 'domino'},
    {hex: '8e8190', name: 'mamba'},
    {hex: '8eabc1', name: 'nepal'},
    {hex: '8f021c', name: 'pohutukawa'},
    {hex: '8f3e33', name: 'el salva'},
    {hex: '8f4b0e', name: 'korma'},
    {hex: '8f8176', name: 'squirrel'},
    {hex: '8fd6b4', name: 'vista blue'},
    {hex: '900020', name: 'burgundy'},
    {hex: '901e1e', name: 'old brick'},
    {hex: '907874', name: 'hemp'},
    {hex: '907b71', name: 'almond frost'},
    {hex: '908d39', name: 'sycamore'},
    {hex: '92000a', name: 'sangria'},
    {hex: '924321', name: 'cumin'},
    {hex: '926f5b', name: 'beaver'},
    {hex: '928573', name: 'stonewall'},
    {hex: '928590', name: 'venus'},
    {hex: '9370db', name: 'medium purple'},
    {hex: '93ccea', name: 'cornflower'},
    {hex: '93dfb8', name: 'algae green'},
    {hex: '944747', name: 'copper rust'},
    {hex: '948771', name: 'arrowtown'},
    {hex: '950015', name: 'scarlett'},
    {hex: '956387', name: 'strikemaster'},
    {hex: '959396', name: 'mountain mist'},
    {hex: '960018', name: 'carmine'},
    {hex: '964b00', name: 'brown'},
    {hex: '967059', name: 'leather'},
    {hex: '9678b6', name: 'purple mountains majesty'},
    {hex: '967bb6', name: 'lavender purple'},
    {hex: '96a8a1', name: 'pewter'},
    {hex: '96bbab', name: 'summer green'},
    {hex: '97605d', name: 'au chico'},
    {hex: '9771b5', name: 'wisteria'},
    {hex: '97cd2d', name: 'atlantis'},
    {hex: '983d61', name: 'vin rouge'},
    {hex: '9874d3', name: 'lilac bush'},
    {hex: '98777b', name: 'bazaar'},
    {hex: '98811b', name: 'hacienda'},
    {hex: '988d77', name: 'pale oyster'},
    {hex: '98ff98', name: 'mint green'},
    {hex: '990066', name: 'fresh eggplant'},
    {hex: '991199', name: 'violet eggplant'},
    {hex: '991613', name: 'tamarillo'},
    {hex: '991b07', name: 'totem pole'},
    {hex: '996666', name: 'copper rose'},
    {hex: '9966cc', name: 'amethyst'},
    {hex: '997a8d', name: 'mountbatten pink'},
    {hex: '9999cc', name: 'blue bell'},
    {hex: '9a3820', name: 'prairie sand'},
    {hex: '9a6e61', name: 'toast'},
    {hex: '9a9577', name: 'gurkha'},
    {hex: '9ab973', name: 'olivine'},
    {hex: '9ac2b8', name: 'shadow green'},
    {hex: '9b4703', name: 'oregon'},
    {hex: '9b9e8f', name: 'lemon grass'},
    {hex: '9c3336', name: 'stiletto'},
    {hex: '9d5616', name: 'hawaiian tan'},
    {hex: '9dacb7', name: 'gull gray'},
    {hex: '9dc209', name: 'pistachio'},
    {hex: '9de093', name: 'granny smith apple'},
    {hex: '9de5ff', name: 'anakiwa'},
    {hex: '9e5302', name: 'chelsea gem'},
    {hex: '9e5b40', name: 'sepia skin'},
    {hex: '9ea587', name: 'sage'},
    {hex: '9ea91f', name: 'citron'},
    {hex: '9eb1cd', name: 'rock blue'},
    {hex: '9edee0', name: 'morning glory'},
    {hex: '9f381d', name: 'cognac'},
    {hex: '9f821c', name: 'reef gold'},
    {hex: '9f9f9c', name: 'star dust'},
    {hex: '9fa0b1', name: 'santas gray'},
    {hex: '9fd7d3', name: 'sinbad'},
    {hex: '9fdd8c', name: 'feijoa'},
    {hex: 'a02712', name: 'tabasco'},
    {hex: 'a1750d', name: 'buttered rum'},
    {hex: 'a1adb5', name: 'hit gray'},
    {hex: 'a1c50a', name: 'citrus'},
    {hex: 'a1dad7', name: 'aqua island'},
    {hex: 'a1e9de', name: 'water leaf'},
    {hex: 'a2006d', name: 'flirt'},
    {hex: 'a23b6c', name: 'rouge'},
    {hex: 'a26645', name: 'cape palliser'},
    {hex: 'a2aab3', name: 'gray chateau'},
    {hex: 'a2aeab', name: 'edward'},
    {hex: 'a3807b', name: 'pharlap'},
    {hex: 'a397b4', name: 'amethyst smoke'},
    {hex: 'a3e3ed', name: 'blizzard blue'},
    {hex: 'a4a49d', name: 'delta'},
    {hex: 'a4a6d3', name: 'wistful'},
    {hex: 'a4af6e', name: 'green smoke'},
    {hex: 'a50b5e', name: 'jazzberry jam'},
    {hex: 'a59b91', name: 'zorba'},
    {hex: 'a5cb0c', name: 'bahia'},
    {hex: 'a62f20', name: 'roof terracotta'},
    {hex: 'a65529', name: 'paarl'},
    {hex: 'a68b5b', name: 'barley corn'},
    {hex: 'a69279', name: 'donkey brown'},
    {hex: 'a6a29a', name: 'dawn'},
    {hex: 'a72525', name: 'mexican red'},
    {hex: 'a7882c', name: 'luxor gold'},
    {hex: 'a85307', name: 'rich gold'},
    {hex: 'a86515', name: 'reno sand'},
    {hex: 'a86b6b', name: 'coral tree'},
    {hex: 'a8989b', name: 'dusty gray'},
    {hex: 'a899e6', name: 'dull lavender'},
    {hex: 'a8a589', name: 'tallow'},
    {hex: 'a8ae9c', name: 'bud'},
    {hex: 'a8af8e', name: 'locust'},
    {hex: 'a8bd9f', name: 'norway'},
    {hex: 'a8e3bd', name: 'chinook'},
    {hex: 'a9a491', name: 'gray olive'},
    {hex: 'a9acb6', name: 'aluminium'},
    {hex: 'a9b2c3', name: 'cadet blue'},
    {hex: 'a9b497', name: 'schist'},
    {hex: 'a9bdbf', name: 'tower gray'},
    {hex: 'a9bef2', name: 'perano'},
    {hex: 'a9c6c2', name: 'opal'},
    {hex: 'aa375a', name: 'night shadz'},
    {hex: 'aa4203', name: 'fire'},
    {hex: 'aa8b5b', name: 'muesli'},
    {hex: 'aa8d6f', name: 'sandal'},
    {hex: 'aaa5a9', name: 'shady lady'},
    {hex: 'aaa9cd', name: 'logan'},
    {hex: 'aaabb7', name: 'spun pearl'},
    {hex: 'aad6e6', name: 'regent st blue'},
    {hex: 'aaf0d1', name: 'magic mint'},
    {hex: 'ab0563', name: 'lipstick'},
    {hex: 'ab3472', name: 'royal heath'},
    {hex: 'ab917a', name: 'sandrift'},
    {hex: 'aba0d9', name: 'cold purple'},
    {hex: 'aba196', name: 'bronco'},
    {hex: 'ac8a56', name: 'limed oak'},
    {hex: 'ac91ce', name: 'east side'},
    {hex: 'ac9e22', name: 'lemon ginger'},
    {hex: 'aca494', name: 'napa'},
    {hex: 'aca586', name: 'hillary'},
    {hex: 'aca59f', name: 'cloudy'},
    {hex: 'acacac', name: 'silver chalice'},
    {hex: 'acb78e', name: 'swamp green'},
    {hex: 'accbb1', name: 'spring rain'},
    {hex: 'acdd4d', name: 'conifer'},
    {hex: 'ace1af', name: 'celadon'},
    {hex: 'ad781b', name: 'mandalay'},
    {hex: 'adbed1', name: 'casper'},
    {hex: 'addfad', name: 'moss green'},
    {hex: 'ade6c4', name: 'padua'},
    {hex: 'adff2f', name: 'green yellow'},
    {hex: 'ae4560', name: 'hippie pink'},
    {hex: 'ae6020', name: 'desert'},
    {hex: 'ae809e', name: 'bouquet'},
    {hex: 'af4035', name: 'medium carmine'},
    {hex: 'af4d43', name: 'apple blossom'},
    {hex: 'af593e', name: 'brown rust'},
    {hex: 'af8751', name: 'driftwood'},
    {hex: 'af8f2c', name: 'alpine'},
    {hex: 'af9f1c', name: 'lucky'},
    {hex: 'afa09e', name: 'martini'},
    {hex: 'afb1b8', name: 'bombay'},
    {hex: 'afbdd9', name: 'pigeon post'},
    {hex: 'b04c6a', name: 'cadillac'},
    {hex: 'b05d54', name: 'matrix'},
    {hex: 'b05e81', name: 'tapestry'},
    {hex: 'b06608', name: 'mai tai'},
    {hex: 'b09a95', name: 'del rio'},
    {hex: 'b0e0e6', name: 'powder blue'},
    {hex: 'b0e313', name: 'inch worm'},
    {hex: 'b10000', name: 'bright red'},
    {hex: 'b14a0b', name: 'vesuvius'},
    {hex: 'b1610b', name: 'pumpkin skin'},
    {hex: 'b16d52', name: 'santa fe'},
    {hex: 'b19461', name: 'teak'},
    {hex: 'b1e2c1', name: 'fringy flower'},
    {hex: 'b1f4e7', name: 'ice cold'},
    {hex: 'b20931', name: 'shiraz'},
    {hex: 'b2a1ea', name: 'biloba flower'},
    {hex: 'b32d29', name: 'tall poppy'},
    {hex: 'b35213', name: 'fiery orange'},
    {hex: 'b38007', name: 'hot toddy'},
    {hex: 'b3af95', name: 'taupe gray'},
    {hex: 'b3c110', name: 'la rioja'},
    {hex: 'b43332', name: 'well read'},
    {hex: 'b44668', name: 'blush'},
    {hex: 'b4cfd3', name: 'jungle mist'},
    {hex: 'b57281', name: 'turkish rose'},
    {hex: 'b57edc', name: 'lavender'},
    {hex: 'b5a27f', name: 'mongoose'},
    {hex: 'b5b35c', name: 'olive green'},
    {hex: 'b5d2ce', name: 'jet stream'},
    {hex: 'b5ecdf', name: 'cruise'},
    {hex: 'b6316c', name: 'hibiscus'},
    {hex: 'b69d98', name: 'thatch'},
    {hex: 'b6b095', name: 'heathered gray'},
    {hex: 'b6baa4', name: 'eagle'},
    {hex: 'b6d1ea', name: 'spindle'},
    {hex: 'b6d3bf', name: 'gum leaf'},
    {hex: 'b7410e', name: 'rust'},
    {hex: 'b78e5c', name: 'muddy waters'},
    {hex: 'b7a214', name: 'sahara'},
    {hex: 'b7a458', name: 'husk'},
    {hex: 'b7b1b1', name: 'nobel'},
    {hex: 'b7c3d0', name: 'heather'},
    {hex: 'b7f0be', name: 'madang'},
    {hex: 'b81104', name: 'milano red'},
    {hex: 'b87333', name: 'copper'},
    {hex: 'b8b56a', name: 'gimblet'},
    {hex: 'b8c1b1', name: 'green spring'},
    {hex: 'b8c25d', name: 'celery'},
    {hex: 'b8e0f9', name: 'sail'},
    {hex: 'b94e48', name: 'chestnut'},
    {hex: 'b95140', name: 'crail'},
    {hex: 'b98d28', name: 'marigold'},
    {hex: 'b9c46a', name: 'wild willow'},
    {hex: 'b9c8ac', name: 'rainee'},
    {hex: 'ba0101', name: 'guardsman red'},
    {hex: 'ba450c', name: 'rock spray'},
    {hex: 'ba6f1e', name: 'bourbon'},
    {hex: 'ba7f03', name: 'pirate gold'},
    {hex: 'bab1a2', name: 'nomad'},
    {hex: 'bac7c9', name: 'submarine'},
    {hex: 'baeef9', name: 'charlotte'},
    {hex: 'bb3385', name: 'medium red violet'},
    {hex: 'bb8983', name: 'brandy rose'},
    {hex: 'bbd009', name: 'rio grande'},
    {hex: 'bbd7c1', name: 'surf'},
    {hex: 'bcc9c2', name: 'powder ash'},
    {hex: 'bd5e2e', name: 'tuscany'},
    {hex: 'bd978e', name: 'quicksand'},
    {hex: 'bdb1a8', name: 'silk'},
    {hex: 'bdb2a1', name: 'malta'},
    {hex: 'bdb3c7', name: 'chatelle'},
    {hex: 'bdbbd7', name: 'lavender gray'},
    {hex: 'bdbdc6', name: 'french gray'},
    {hex: 'bdc8b3', name: 'clay ash'},
    {hex: 'bdc9ce', name: 'loblolly'},
    {hex: 'bdedfd', name: 'french pass'},
    {hex: 'bea6c3', name: 'london hue'},
    {hex: 'beb5b7', name: 'pink swan'},
    {hex: 'bede0d', name: 'fuego'},
    {hex: 'bf5500', name: 'rose of sharon'},
    {hex: 'bfb8b0', name: 'tide'},
    {hex: 'bfbed8', name: 'blue haze'},
    {hex: 'bfc1c2', name: 'silver sand'},
    {hex: 'bfc921', name: 'key lime pie'},
    {hex: 'bfdbe2', name: 'ziggurat'},
    // {hex: 'bfff00', name: 'lime'},
    {hex: 'c02b18', name: 'thunderbird'},
    {hex: 'c04737', name: 'mojo'},
    {hex: 'c08081', name: 'old rose'},
    {hex: 'c0c0c0', name: 'silver'},
    {hex: 'c0d3b9', name: 'pale leaf'},
    {hex: 'c0d8b6', name: 'pixie green'},
    {hex: 'c1440e', name: 'tia maria'},
    {hex: 'c154c1', name: 'fuchsia pink'},
    {hex: 'c1a004', name: 'buddha gold'},
    {hex: 'c1b7a4', name: 'bison hide'},
    {hex: 'c1bab0', name: 'tea'},
    {hex: 'c1becd', name: 'gray suit'},
    {hex: 'c1d7b0', name: 'sprout'},
    {hex: 'c1f07c', name: 'sulu'},
    {hex: 'c26b03', name: 'indochine'},
    {hex: 'c2955d', name: 'twine'},
    {hex: 'c2bdb6', name: 'cotton seed'},
    {hex: 'c2cac4', name: 'pumice'},
    {hex: 'c2e8e5', name: 'jagged ice'},
    {hex: 'c32148', name: 'maroon flush'},
    {hex: 'c3b091', name: 'indian khaki'},
    {hex: 'c3bfc1', name: 'pale slate'},
    {hex: 'c3c3bd', name: 'gray nickel'},
    {hex: 'c3cde6', name: 'periwinkle gray'},
    {hex: 'c3d1d1', name: 'tiara'},
    {hex: 'c3ddf9', name: 'tropical blue'},
    {hex: 'c41e3a', name: 'cardinal'},
    {hex: 'c45655', name: 'fuzzy wuzzy brown'},
    {hex: 'c45719', name: 'orange roughy'},
    {hex: 'c4c4bc', name: 'mist gray'},
    {hex: 'c4d0b0', name: 'coriander'},
    {hex: 'c4f4eb', name: 'mint tulip'},
    {hex: 'c54b8c', name: 'mulberry'},
    {hex: 'c59922', name: 'nugget'},
    {hex: 'c5994b', name: 'tussock'},
    {hex: 'c5dbca', name: 'sea mist'},
    {hex: 'c5e17a', name: 'yellow green'},
    {hex: 'c62d42', name: 'brick red'},
    {hex: 'c6726b', name: 'contessa'},
    {hex: 'c69191', name: 'oriental pink'},
    {hex: 'c6a84b', name: 'roti'},
    {hex: 'c6c3b5', name: 'ash'},
    {hex: 'c6c8bd', name: 'kangaroo'},
    {hex: 'c6e610', name: 'las palmas'},
    {hex: 'c7031e', name: 'monza'},
    {hex: 'c71585', name: 'red violet'},
    {hex: 'c7bca2', name: 'coral reef'},
    {hex: 'c7c1ff', name: 'melrose'},
    {hex: 'c7c4bf', name: 'cloud'},
    {hex: 'c7c9d5', name: 'ghost'},
    {hex: 'c7cd90', name: 'pine glade'},
    {hex: 'c7dde5', name: 'botticelli'},
    {hex: 'c88a65', name: 'antique brass'},
    {hex: 'c8a2c8', name: 'lilac'},
    {hex: 'c8a528', name: 'hokey pokey'},
    {hex: 'c8aabf', name: 'lily'},
    {hex: 'c8b568', name: 'laser'},
    {hex: 'c8e3d7', name: 'edgewater'},
    {hex: 'c96323', name: 'piper'},
    {hex: 'c99415', name: 'pizza'},
    {hex: 'c9a0dc', name: 'light wisteria'},
    {hex: 'c9b29b', name: 'rodeo dust'},
    {hex: 'c9b35b', name: 'sundance'},
    {hex: 'c9b93b', name: 'earls green'},
    {hex: 'c9c0bb', name: 'silver rust'},
    {hex: 'c9d9d2', name: 'conch'},
    {hex: 'c9ffa2', name: 'reef'},
    {hex: 'c9ffe5', name: 'aero blue'},
    {hex: 'ca3435', name: 'flush mahogany'},
    {hex: 'cabb48', name: 'turmeric'},
    {hex: 'cadcd4', name: 'paris white'},
    {hex: 'cae00d', name: 'bitter lemon'},
    {hex: 'cae6da', name: 'skeptic'},
    {hex: 'cb8fa9', name: 'viola'},
    {hex: 'cbcab6', name: 'foggy gray'},
    {hex: 'cbd3b0', name: 'green mist'},
    {hex: 'cbdbd6', name: 'nebula'},
    {hex: 'cc3333', name: 'persian red'},
    {hex: 'cc5500', name: 'burnt orange'},
    {hex: 'cc7722', name: 'ochre'},
    {hex: 'cc8899', name: 'puce'},
    {hex: 'cccaa8', name: 'thistle green'},
    {hex: 'ccccff', name: 'periwinkle'},
    {hex: 'ccff00', name: 'electric lime'},
    {hex: 'cd5700', name: 'tenn'},
    {hex: 'cd5c5c', name: 'chestnut rose'},
    {hex: 'cd8429', name: 'brandy punch'},
    {hex: 'cdf4ff', name: 'onahau'},
    {hex: 'ceb98f', name: 'sorrell brown'},
    {hex: 'cebaba', name: 'cold turkey'},
    {hex: 'cec291', name: 'yuma'},
    {hex: 'cec7a7', name: 'chino'},
    {hex: 'cfa39d', name: 'eunry'},
    {hex: 'cfb53b', name: 'old gold'},
    {hex: 'cfdccf', name: 'tasman'},
    {hex: 'cfe5d2', name: 'surf crest'},
    {hex: 'cff9f3', name: 'humming bird'},
    {hex: 'cffaf4', name: 'scandal'},
    {hex: 'd05f04', name: 'red stage'},
    {hex: 'd06da1', name: 'hopbush'},
    {hex: 'd07d12', name: 'meteor'},
    {hex: 'd0bef8', name: 'perfume'},
    {hex: 'd0c0e5', name: 'prelude'},
    {hex: 'd0f0c0', name: 'tea green'},
    {hex: 'd18f1b', name: 'geebung'},
    {hex: 'd1bea8', name: 'vanilla'},
    {hex: 'd1c6b4', name: 'soft amber'},
    {hex: 'd1d2ca', name: 'celeste'},
    {hex: 'd1d2dd', name: 'mischka'},
    {hex: 'd1e231', name: 'pear'},
    {hex: 'd2691e', name: 'hot cinnamon'},
    {hex: 'd27d46', name: 'raw sienna'},
    {hex: 'd29eaa', name: 'careys pink'},
    {hex: 'd2b48c', name: 'tan'},
    {hex: 'd2da97', name: 'deco'},
    {hex: 'd2f6de', name: 'blue romance'},
    {hex: 'd2f8b0', name: 'gossip'},
    {hex: 'd3cbba', name: 'sisal'},
    {hex: 'd3cdc5', name: 'swirl'},
    {hex: 'd47494', name: 'charm'},
    {hex: 'd4b6af', name: 'clam shell'},
    {hex: 'd4bf8d', name: 'straw'},
    {hex: 'd4c4a8', name: 'akaroa'},
    {hex: 'd4cd16', name: 'bird flower'},
    {hex: 'd4d7d9', name: 'iron'},
    {hex: 'd4dfe2', name: 'geyser'},
    {hex: 'd4e2fc', name: 'hawkes blue'},
    {hex: 'd54600', name: 'grenadier'},
    {hex: 'd591a4', name: 'can can'},
    {hex: 'd59a6f', name: 'whiskey'},
    {hex: 'd5d195', name: 'winter hazel'},
    {hex: 'd5f6e3', name: 'granny apple'},
    {hex: 'd69188', name: 'my pink'},
    {hex: 'd6c562', name: 'tacha'},
    {hex: 'd6cef6', name: 'moon raker'},
    {hex: 'd6d6d1', name: 'quill gray'},
    {hex: 'd6ffdb', name: 'snowy mint'},
    {hex: 'd7837f', name: 'new york pink'},
    {hex: 'd7c498', name: 'pavlova'},
    {hex: 'd7d0ff', name: 'fog'},
    {hex: 'd84437', name: 'valencia'},
    {hex: 'd87c63', name: 'japonica'},
    {hex: 'd8bfd8', name: 'thistle'},
    {hex: 'd8c2d5', name: 'maverick'},
    {hex: 'd8fcfa', name: 'foam'},
    {hex: 'd94972', name: 'cabaret'},
    {hex: 'd99376', name: 'burning sand'},
    {hex: 'd9b99b', name: 'cameo'},
    {hex: 'd9d6cf', name: 'timberwolf'},
    {hex: 'd9dcc1', name: 'tana'},
    {hex: 'd9e4f5', name: 'link water'},
    {hex: 'd9f7ff', name: 'mabel'},
    {hex: 'da3287', name: 'cerise'},
    {hex: 'da5b38', name: 'flame pea'},
    {hex: 'da6304', name: 'bamboo'},
    {hex: 'da6a41', name: 'red damask'},
    {hex: 'da70d6', name: 'orchid'},
    {hex: 'da8a67', name: 'copperfield'},
    {hex: 'daa520', name: 'golden grass'},
    {hex: 'daecd6', name: 'zanah'},
    {hex: 'daf4f0', name: 'iceberg'},
    {hex: 'dafaff', name: 'oyster bay'},
    {hex: 'db5079', name: 'cranberry'},
    {hex: 'db9690', name: 'petite orchid'},
    {hex: 'db995e', name: 'di serria'},
    {hex: 'dbdbdb', name: 'alto'},
    {hex: 'dbfff8', name: 'frosted mint'},
    {hex: 'dc143c', name: 'crimson'},
    {hex: 'dc4333', name: 'punch'},
    {hex: 'dcb20c', name: 'galliano'},
    {hex: 'dcb4bc', name: 'blossom'},
    {hex: 'dcd747', name: 'wattle'},
    {hex: 'dcd9d2', name: 'westar'},
    {hex: 'dcddcc', name: 'moon mist'},
    {hex: 'dcedb4', name: 'caper'},
    {hex: 'dcf0ea', name: 'swans down'},
    {hex: 'ddd6d5', name: 'swiss coffee'},
    {hex: 'ddf9f1', name: 'white ice'},
    {hex: 'de3163', name: 'cerise red'},
    {hex: 'de6360', name: 'roman'},
    {hex: 'dea681', name: 'tumbleweed'},
    {hex: 'deba13', name: 'gold tips'},
    {hex: 'dec196', name: 'brandy'},
    {hex: 'decbc6', name: 'wafer'},
    {hex: 'ded4a4', name: 'sapling'},
    {hex: 'ded717', name: 'barberry'},
    {hex: 'dee5c0', name: 'beryl green'},
    {hex: 'def5ff', name: 'pattens blue'},
    {hex: 'df73ff', name: 'heliotrope'},
    {hex: 'dfbe6f', name: 'apache'},
    {hex: 'dfcd6f', name: 'chenin'},
    {hex: 'dfcfdb', name: 'lola'},
    {hex: 'dfecda', name: 'willow brook'},
    {hex: 'dfff00', name: 'chartreuse yellow'},
    {hex: 'e0b0ff', name: 'mauve'},
    {hex: 'e0b646', name: 'anzac'},
    {hex: 'e0b974', name: 'harvest gold'},
    {hex: 'e0c095', name: 'calico'},
    {hex: 'e0ffff', name: 'baby blue'},
    {hex: 'e16865', name: 'sunglo'},
    {hex: 'e1bc64', name: 'equator'},
    {hex: 'e1c0c8', name: 'pink flare'},
    {hex: 'e1e6d6', name: 'periglacial blue'},
    {hex: 'e1ead4', name: 'kidnapper'},
    {hex: 'e1f6e8', name: 'tara'},
    {hex: 'e25465', name: 'mandy'},
    {hex: 'e2725b', name: 'terracotta'},
    {hex: 'e28913', name: 'golden bell'},
    {hex: 'e292c0', name: 'shocking'},
    {hex: 'e29418', name: 'dixie'},
    {hex: 'e29cd2', name: 'light orchid'},
    {hex: 'e2d8ed', name: 'snuff'},
    {hex: 'e2ebed', name: 'mystic'},
    {hex: 'e2f3ec', name: 'apple green'},
    {hex: 'e30b5c', name: 'razzmatazz'},
    {hex: 'e32636', name: 'alizarin crimson'},
    {hex: 'e34234', name: 'cinnabar'},
    {hex: 'e3bebe', name: 'cavern pink'},
    {hex: 'e3f5e1', name: 'peppermint'},
    {hex: 'e3f988', name: 'mindaro'},
    {hex: 'e47698', name: 'deep blush'},
    {hex: 'e49b0f', name: 'gamboge'},
    {hex: 'e4c2d5', name: 'melanie'},
    {hex: 'e4cfde', name: 'twilight'},
    {hex: 'e4d1c0', name: 'bone'},
    {hex: 'e4d422', name: 'sunflower'},
    {hex: 'e4d5b7', name: 'grain brown'},
    {hex: 'e4d69b', name: 'zombie'},
    {hex: 'e4f6e7', name: 'frostee'},
    {hex: 'e4ffd1', name: 'snow flurry'},
    {hex: 'e52b50', name: 'amaranth'},
    {hex: 'e5841b', name: 'zest'},
    {hex: 'e5ccc9', name: 'dust storm'},
    {hex: 'e5d7bd', name: 'stark white'},
    {hex: 'e5d8af', name: 'hampton'},
    {hex: 'e5e0e1', name: 'bon jour'},
    {hex: 'e5e5e5', name: 'mercury'},
    {hex: 'e5f9f6', name: 'polar'},
    {hex: 'e64e03', name: 'trinidad'},
    {hex: 'e6be8a', name: 'gold sand'},
    {hex: 'e6bea5', name: 'cashmere'},
    {hex: 'e6d7b9', name: 'double spanish white'},
    {hex: 'e6e4d4', name: 'satin linen'},
    {hex: 'e6f2ea', name: 'harp'},
    {hex: 'e6f8f3', name: 'off green'},
    {hex: 'e6ffe9', name: 'hint of green'},
    {hex: 'e6ffff', name: 'tranquil'},
    {hex: 'e77200', name: 'mango tango'},
    {hex: 'e7730a', name: 'christine'},
    {hex: 'e79f8c', name: 'tonys pink'},
    {hex: 'e79fc4', name: 'kobi'},
    {hex: 'e7bcb4', name: 'rose fog'},
    {hex: 'e7bf05', name: 'corn'},
    {hex: 'e7cd8c', name: 'putty'},
    {hex: 'e7ece6', name: 'gray nurse'},
    {hex: 'e7f8ff', name: 'lily white'},
    {hex: 'e7feff', name: 'bubbles'},
    {hex: 'e89928', name: 'fire bush'},
    {hex: 'e8b9b3', name: 'shilo'},
    {hex: 'e8e0d5', name: 'pearl bush'},
    {hex: 'e8ebe0', name: 'green white'},
    {hex: 'e8f1d4', name: 'chrome white'},
    {hex: 'e8f2eb', name: 'gin'},
    {hex: 'e8f5f2', name: 'aqua squeeze'},
    {hex: 'e96e00', name: 'clementine'},
    {hex: 'e97451', name: 'burnt sienna'},
    {hex: 'e97c07', name: 'tahiti gold'},
    {hex: 'e9cecd', name: 'oyster pink'},
    {hex: 'e9d75a', name: 'confetti'},
    {hex: 'e9e3e3', name: 'ebb'},
    {hex: 'e9f8ed', name: 'ottoman'},
    {hex: 'e9fffd', name: 'clear day'},
    {hex: 'ea88a8', name: 'carissma'},
    {hex: 'eaae69', name: 'porsche'},
    {hex: 'eab33b', name: 'tulip tree'},
    {hex: 'eac674', name: 'rob roy'},
    {hex: 'eadab8', name: 'raffia'},
    {hex: 'eae8d4', name: 'white rock'},
    {hex: 'eaf6ee', name: 'panache'},
    {hex: 'eaf6ff', name: 'solitude'},
    {hex: 'eaf9f5', name: 'aqua spring'},
    {hex: 'eafffe', name: 'dew'},
    {hex: 'eb9373', name: 'apricot'},
    {hex: 'ebc2af', name: 'zinnwaldite'},
    {hex: 'eca927', name: 'fuel yellow'},
    {hex: 'ecc54e', name: 'ronchi'},
    {hex: 'ecc7ee', name: 'french lilac'},
    {hex: 'eccdb9', name: 'just right'},
    {hex: 'ece090', name: 'wild rice'},
    {hex: 'ecebbd', name: 'fall green'},
    {hex: 'ecebce', name: 'aths special'},
    {hex: 'ecf245', name: 'starship'},
    {hex: 'ed0a3f', name: 'red ribbon'},
    {hex: 'ed7a1c', name: 'tango'},
    {hex: 'ed9121', name: 'carrot orange'},
    {hex: 'ed989e', name: 'sea pink'},
    {hex: 'edb381', name: 'tacao'},
    {hex: 'edc9af', name: 'desert sand'},
    {hex: 'edcdab', name: 'pancho'},
    {hex: 'eddcb1', name: 'chamois'},
    {hex: 'edea99', name: 'primrose'},
    {hex: 'edf5dd', name: 'frost'},
    {hex: 'edf5f5', name: 'aqua haze'},
    {hex: 'edf6ff', name: 'zumthor'},
    {hex: 'edf9f1', name: 'narvik'},
    {hex: 'edfc84', name: 'honeysuckle'},
    {hex: 'ee82ee', name: 'lavender magenta'},
    {hex: 'eec1be', name: 'beauty bush'},
    {hex: 'eed794', name: 'chalky'},
    {hex: 'eed9c4', name: 'almond'},
    {hex: 'eedc82', name: 'flax'},
    {hex: 'eededa', name: 'bizarre'},
    {hex: 'eee3ad', name: 'double colonial white'},
    {hex: 'eeeee8', name: 'cararra'},
    {hex: 'eeef78', name: 'manz'},
    {hex: 'eef0c8', name: 'tahuna sands'},
    {hex: 'eef0f3', name: 'athens gray'},
    {hex: 'eef3c3', name: 'tusk'},
    {hex: 'eef4de', name: 'loafer'},
    {hex: 'eef6f7', name: 'catskill white'},
    {hex: 'eefdff', name: 'twilight blue'},
    {hex: 'eeff9a', name: 'jonquil'},
    {hex: 'eeffe2', name: 'rice flower'},
    {hex: 'ef863f', name: 'jaffa'},
    {hex: 'efefef', name: 'gallery'},
    {hex: 'eff2f3', name: 'porcelain'},
    {hex: 'f091a9', name: 'mauvelous'},
    {hex: 'f0d52d', name: 'golden dream'},
    {hex: 'f0db7d', name: 'golden sand'},
    {hex: 'f0dc82', name: 'buff'},
    {hex: 'f0e2ec', name: 'prim'},
    {hex: 'f0e68c', name: 'khaki'},
    {hex: 'f0eefd', name: 'selago'},
    {hex: 'f0eeff', name: 'titan white'},
    {hex: 'f0f8ff', name: 'alice blue'},
    {hex: 'f0fcea', name: 'feta'},
    {hex: 'f18200', name: 'gold drop'},
    {hex: 'f19bab', name: 'wewak'},
    {hex: 'f1e788', name: 'sahara sand'},
    {hex: 'f1e9d2', name: 'parchment'},
    {hex: 'f1e9ff', name: 'blue chalk'},
    {hex: 'f1eec1', name: 'mint julep'},
    {hex: 'f1f1f1', name: 'seashell'},
    {hex: 'f1f7f2', name: 'saltpan'},
    {hex: 'f1ffad', name: 'tidal'},
    {hex: 'f1ffc8', name: 'chiffon'},
    {hex: 'f2552a', name: 'flamingo'},
    {hex: 'f28500', name: 'tangerine'},
    {hex: 'f2c3b2', name: 'mandys pink'},
    {hex: 'f2f2f2', name: 'concrete'},
    {hex: 'f2fafa', name: 'black squeeze'},
    {hex: 'f34723', name: 'pomegranate'},
    {hex: 'f3ad16', name: 'buttercup'},
    {hex: 'f3d69d', name: 'new orleans'},
    {hex: 'f3d9df', name: 'vanilla ice'},
    {hex: 'f3e7bb', name: 'sidecar'},
    {hex: 'f3e9e5', name: 'dawn pink'},
    {hex: 'f3edcf', name: 'wheatfield'},
    {hex: 'f3fb62', name: 'canary'},
    {hex: 'f3fbd4', name: 'orinoco'},
    {hex: 'f3ffd8', name: 'carla'},
    {hex: 'f400a1', name: 'hollywood cerise'},
    {hex: 'f4a460', name: 'sandy brown'},
    {hex: 'f4c430', name: 'saffron'},
    {hex: 'f4d81c', name: 'ripe lemon'},
    {hex: 'f4ebd3', name: 'janna'},
    {hex: 'f4f2ee', name: 'pampas'},
    {hex: 'f4f4f4', name: 'wild sand'},
    {hex: 'f4f8ff', name: 'zircon'},
    {hex: 'f57584', name: 'froly'},
    {hex: 'f5c85c', name: 'cream can'},
    {hex: 'f5c999', name: 'manhattan'},
    {hex: 'f5d5a0', name: 'maize'},
    {hex: 'f5deb3', name: 'wheat'},
    {hex: 'f5e7a2', name: 'sandwisp'},
    {hex: 'f5e7e2', name: 'pot pourri'},
    {hex: 'f5e9d3', name: 'albescent white'},
    {hex: 'f5edef', name: 'soft peach'},
    {hex: 'f5f3e5', name: 'ecru white'},
    {hex: 'f5f5dc', name: 'beige'},
    {hex: 'f5fb3d', name: 'golden fizz'},
    {hex: 'f5ffbe', name: 'australian mint'},
    {hex: 'f64a8a', name: 'french rose'},
    {hex: 'f653a6', name: 'brilliant rose'},
    {hex: 'f6a4c9', name: 'illusion'},
    {hex: 'f6f0e6', name: 'merino'},
    {hex: 'f6f7f7', name: 'black haze'},
    {hex: 'f6ffdc', name: 'spring sun'},
    {hex: 'f7468a', name: 'violet red'},
    {hex: 'f77703', name: 'chilean fire'},
    {hex: 'f77fbe', name: 'persian pink'},
    {hex: 'f7b668', name: 'rajah'},
    {hex: 'f7c8da', name: 'azalea'},
    {hex: 'f7dbe6', name: 'we peep'},
    {hex: 'f7f2e1', name: 'quarter spanish white'},
    {hex: 'f7f5fa', name: 'whisper'},
    {hex: 'f7faf7', name: 'snow drift'},
    {hex: 'f8b853', name: 'casablanca'},
    {hex: 'f8c3df', name: 'chantilly'},
    {hex: 'f8d9e9', name: 'cherub'},
    {hex: 'f8db9d', name: 'marzipan'},
    {hex: 'f8dd5c', name: 'energy yellow'},
    {hex: 'f8e4bf', name: 'givry'},
    {hex: 'f8f0e8', name: 'white linen'},
    {hex: 'f8f4ff', name: 'magnolia'},
    {hex: 'f8f6f1', name: 'spring wood'},
    {hex: 'f8f7dc', name: 'coconut cream'},
    {hex: 'f8f7fc', name: 'white lilac'},
    {hex: 'f8f8f7', name: 'desert storm'},
    {hex: 'f8f99c', name: 'texas'},
    {hex: 'f8facd', name: 'corn field'},
    {hex: 'f8fdd3', name: 'mimosa'},
    {hex: 'f95a61', name: 'carnation'},
    {hex: 'f9bf58', name: 'saffron mango'},
    {hex: 'f9e0ed', name: 'carousel pink'},
    {hex: 'f9e4bc', name: 'dairy cream'},
    {hex: 'f9e663', name: 'portica'},
    {hex: 'f9eaf3', name: 'amour'},
    {hex: 'f9f8e4', name: 'rum swizzle'},
    {hex: 'f9ff8b', name: 'dolly'},
    {hex: 'f9fff6', name: 'sugar cane'},
    {hex: 'fa7814', name: 'ecstasy'},
    {hex: 'fa9d5a', name: 'tan hide'},
    {hex: 'fad3a2', name: 'corvette'},
    {hex: 'fadfad', name: 'peach yellow'},
    {hex: 'fae600', name: 'turbo'},
    {hex: 'faeab9', name: 'astra'},
    {hex: 'faeccc', name: 'champagne'},
    {hex: 'faf0e6', name: 'linen'},
    {hex: 'faf3f0', name: 'fantasy'},
    {hex: 'faf7d6', name: 'citrine white'},
    {hex: 'fafafa', name: 'alabaster'},
    {hex: 'fafde4', name: 'hint of yellow'},
    {hex: 'faffa4', name: 'milan'},
    {hex: 'fb607f', name: 'brink pink'},
    {hex: 'fb8989', name: 'geraldine'},
    {hex: 'fba0e3', name: 'lavender rose'},
    {hex: 'fba129', name: 'sea buckthorn'},
    {hex: 'fbac13', name: 'sun'},
    {hex: 'fbaed2', name: 'lavender pink'},
    {hex: 'fbb2a3', name: 'rose bud'},
    {hex: 'fbbeda', name: 'cupid'},
    {hex: 'fbcce7', name: 'classic rose'},
    {hex: 'fbceb1', name: 'apricot peach'},
    {hex: 'fbe7b2', name: 'banana mania'},
    {hex: 'fbe870', name: 'marigold yellow'},
    {hex: 'fbe96c', name: 'festival'},
    {hex: 'fbea8c', name: 'sweet corn'},
    {hex: 'fbec5d', name: 'candy corn'},
    {hex: 'fbf9f9', name: 'hint of red'},
    {hex: 'fbffba', name: 'shalimar'},
    {hex: 'fc0fc0', name: 'shocking pink'},
    {hex: 'fc80a5', name: 'tickle me pink'},
    {hex: 'fc9c1d', name: 'tree poppy'},
    {hex: 'fcc01e', name: 'lightning yellow'},
    {hex: 'fcd667', name: 'goldenrod'},
    {hex: 'fcd917', name: 'candlelight'},
    {hex: 'fcda98', name: 'cherokee'},
    {hex: 'fcf4d0', name: 'double pearl lusta'},
    {hex: 'fcf4dc', name: 'pearl lusta'},
    {hex: 'fcf8f7', name: 'vista white'},
    {hex: 'fcfbf3', name: 'bianca'},
    {hex: 'fcfeda', name: 'moon glow'},
    {hex: 'fcffe7', name: 'china ivory'},
    {hex: 'fcfff9', name: 'ceramic'},
    {hex: 'fd0e35', name: 'torch red'},
    {hex: 'fd5b78', name: 'wild watermelon'},
    {hex: 'fd7b33', name: 'crusta'},
    {hex: 'fd7c07', name: 'sorbus'},
    {hex: 'fd9fa2', name: 'sweet pink'},
    {hex: 'fdd5b1', name: 'light apricot'},
    {hex: 'fdd7e4', name: 'pig pink'},
    {hex: 'fde1dc', name: 'cinderella'},
    {hex: 'fde295', name: 'golden glow'},
    {hex: 'fde910', name: 'lemon'},
    {hex: 'fdf5e6', name: 'old lace'},
    {hex: 'fdf6d3', name: 'half colonial white'},
    {hex: 'fdf7ad', name: 'drover'},
    {hex: 'fdfeb8', name: 'pale prim'},
    {hex: 'fdffd5', name: 'cumulus'},
    {hex: 'fe28a2', name: 'persian rose'},
    {hex: 'fe4c40', name: 'sunset orange'},
    {hex: 'fe6f5e', name: 'bittersweet'},
    {hex: 'fe9d04', name: 'california'},
    {hex: 'fea904', name: 'yellow sea'},
    {hex: 'febaad', name: 'melon'},
    {hex: 'fed33c', name: 'bright sun'},
    {hex: 'fed85d', name: 'dandelion'},
    {hex: 'fedb8d', name: 'salomie'},
    {hex: 'fee5ac', name: 'cape honey'},
    {hex: 'feebf3', name: 'remy'},
    {hex: 'feefce', name: 'oasis'},
    {hex: 'fef0ec', name: 'bridesmaid'},
    {hex: 'fef2c7', name: 'beeswax'},
    {hex: 'fef3d8', name: 'bleach white'},
    {hex: 'fef4cc', name: 'pipi'},
    {hex: 'fef4db', name: 'half spanish white'},
    {hex: 'fef4f8', name: 'wisp pink'},
    {hex: 'fef5f1', name: 'provincial pink'},
    {hex: 'fef7de', name: 'half dutch white'},
    {hex: 'fef8e2', name: 'solitaire'},
    {hex: 'fef8ff', name: 'white pointer'},
    {hex: 'fef9e3', name: 'off yellow'},
    {hex: 'fefced', name: 'orange white'},
    {hex: 'ff0000', name: 'red'},
    {hex: 'ff007f', name: 'rose'},
    {hex: 'ff00cc', name: 'purple pizzazz'},
    {hex: 'ff00ff', name: 'magenta / fuchsia'},
    {hex: 'ff2400', name: 'scarlet'},
    {hex: 'ff3399', name: 'wild strawberry'},
    {hex: 'ff33cc', name: 'razzle dazzle rose'},
    {hex: 'ff355e', name: 'radical red'},
    {hex: 'ff3f34', name: 'red orange'},
    {hex: 'ff4040', name: 'coral red'},
    {hex: 'ff4d00', name: 'vermilion'},
    {hex: 'ff4f00', name: 'international orange'},
    {hex: 'ff6037', name: 'outrageous orange'},
    {hex: 'ff6347', name: 'tomato'},
    {hex: 'ff6600', name: 'blaze orange'},
    {hex: 'ff66ff', name: 'pink flamingo'},
    {hex: 'ff681f', name: 'orange'},
    {hex: 'ff69b4', name: 'hot pink'},
    {hex: 'ff6b53', name: 'persimmon'},
    {hex: 'ff6fff', name: 'blush pink'},
    {hex: 'ff7034', name: 'burning orange'},
    {hex: 'ff7518', name: 'pumpkin'},
    {hex: 'ff7d07', name: 'flamenco'},
    {hex: 'ff7f00', name: 'flush orange'},
    {hex: 'ff7f50', name: 'coral'},
    {hex: 'ff8c69', name: 'salmon'},
    {hex: 'ff9000', name: 'pizazz'},
    {hex: 'ff910f', name: 'west side'},
    {hex: 'ff91a4', name: 'pink salmon'},
    {hex: 'ff9933', name: 'neon carrot'},
    {hex: 'ff9966', name: 'atomic tangerine'},
    {hex: 'ff9980', name: 'vivid tangerine'},
    {hex: 'ff9e2c', name: 'sunshade'},
    {hex: 'ffa000', name: 'orange peel'},
    {hex: 'ffa194', name: 'mona lisa'},
    {hex: 'ffa500', name: 'web orange'},
    {hex: 'ffa6c9', name: 'carnation pink'},
    {hex: 'ffab81', name: 'hit pink'},
    {hex: 'ffae42', name: 'yellow orange'},
    {hex: 'ffb0ac', name: 'cornflower lilac'},
    {hex: 'ffb1b3', name: 'sundown'},
    {hex: 'ffb31f', name: 'my sin'},
    {hex: 'ffb555', name: 'texas rose'},
    {hex: 'ffb7d5', name: 'cotton candy'},
    {hex: 'ffb97b', name: 'macaroni and cheese'},
    {hex: 'ffba00', name: 'selective yellow'},
    {hex: 'ffbd5f', name: 'koromiko'},
    {hex: 'ffbf00', name: 'amber'},
    {hex: 'ffc0a8', name: 'wax flower'},
    {hex: 'ffc0cb', name: 'pink'},
    {hex: 'ffc3c0', name: 'your pink'},
    {hex: 'ffc901', name: 'supernova'},
    {hex: 'ffcba4', name: 'flesh'},
    {hex: 'ffcc33', name: 'sunglow'},
    {hex: 'ffcc5c', name: 'golden tainoi'},
    {hex: 'ffcc99', name: 'peach orange'},
    {hex: 'ffcd8c', name: 'chardonnay'},
    {hex: 'ffd1dc', name: 'pastel pink'},
    {hex: 'ffd2b7', name: 'romantic'},
    {hex: 'ffd38c', name: 'grandis'},
    {hex: 'ffd700', name: 'gold'},
    {hex: 'ffd800', name: 'school bus yellow'},
    {hex: 'ffd8d9', name: 'cosmos'},
    {hex: 'ffdb58', name: 'mustard'},
    {hex: 'ffdcd6', name: 'peach schnapps'},
    {hex: 'ffddaf', name: 'caramel'},
    {hex: 'ffddcd', name: 'tuft bush'},
    {hex: 'ffddcf', name: 'watusi'},
    {hex: 'ffddf4', name: 'pink lace'},
    {hex: 'ffdead', name: 'navajo white'},
    {hex: 'ffdeb3', name: 'frangipani'},
    {hex: 'ffe1df', name: 'pippin'},
    {hex: 'ffe1f2', name: 'pale rose'},
    {hex: 'ffe2c5', name: 'negroni'},
    {hex: 'ffe5a0', name: 'cream brulee'},
    {hex: 'ffe5b4', name: 'peach'},
    {hex: 'ffe6c7', name: 'tequila'},
    {hex: 'ffe772', name: 'kournikova'},
    {hex: 'ffeac8', name: 'sandy beach'},
    {hex: 'ffead4', name: 'karry'},
    {hex: 'ffec13', name: 'broom'},
    {hex: 'ffedbc', name: 'colonial white'},
    {hex: 'ffeed8', name: 'derby'},
    {hex: 'ffefa1', name: 'vis vis'},
    {hex: 'ffefc1', name: 'egg white'},
    {hex: 'ffefd5', name: 'papaya whip'},
    {hex: 'ffefec', name: 'fair pink'},
    {hex: 'fff0db', name: 'peach cream'},
    {hex: 'fff0f5', name: 'lavender blush'},
    {hex: 'fff14f', name: 'gorse'},
    {hex: 'fff1b5', name: 'buttermilk'},
    {hex: 'fff1d8', name: 'pink lady'},
    {hex: 'fff1ee', name: 'forget me not'},
    {hex: 'fff1f9', name: 'tutu'},
    {hex: 'fff39d', name: 'picasso'},
    {hex: 'fff3f1', name: 'chardon'},
    {hex: 'fff46e', name: 'paris daisy'},
    {hex: 'fff4ce', name: 'barley white'},
    {hex: 'fff4dd', name: 'egg sour'},
    {hex: 'fff4e0', name: 'sazerac'},
    {hex: 'fff4e8', name: 'serenade'},
    {hex: 'fff4f3', name: 'chablis'},
    {hex: 'fff5ee', name: 'seashell peach'},
    {hex: 'fff5f3', name: 'sauvignon'},
    {hex: 'fff6d4', name: 'milk punch'},
    {hex: 'fff6df', name: 'varden'},
    {hex: 'fff6f5', name: 'rose white'},
    {hex: 'fff8d1', name: 'baja white'},
    {hex: 'fff9e2', name: 'gin fizz'},
    {hex: 'fff9e6', name: 'early dawn'},
    {hex: 'fffacd', name: 'lemon chiffon'},
    {hex: 'fffaf4', name: 'bridal heath'},
    {hex: 'fffbdc', name: 'scotch mist'},
    {hex: 'fffbf9', name: 'soapstone'},
    {hex: 'fffc99', name: 'witch haze'},
    {hex: 'fffcea', name: 'buttery white'},
    {hex: 'fffcee', name: 'island spice'},
    {hex: 'fffdd0', name: 'cream'},
    {hex: 'fffde6', name: 'chilean heath'},
    {hex: 'fffde8', name: 'travertine'},
    {hex: 'fffdf3', name: 'orchid white'},
    {hex: 'fffdf4', name: 'quarter pearl lusta'},
    {hex: 'fffee1', name: 'half and half'},
    {hex: 'fffeec', name: 'apricot white'},
    {hex: 'fffef0', name: 'rice cake'},
    {hex: 'fffef6', name: 'black white'},
    {hex: 'fffefd', name: 'romance'},
    {hex: 'ffff00', name: 'yellow'},
    {hex: 'ffff66', name: 'laser lemon'},
    {hex: 'ffff99', name: 'pale canary'},
    {hex: 'ffffb4', name: 'portafino'},
    {hex: 'fffff0', name: 'ivory'},
    {hex: 'ffffff', name: 'white'}
    ]